### ISSUE TITLE
Fix duplicate error from log file

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/godwoken_explorer#1057]
Check server error.log and find errors that appear many times

**Comment by zmcNotafraid** [comment]
- [ ] not exist route
```
2022-09-16 18:55:30.685 [error] #PID<0.18308.0> running GodwokenExplorerWeb.Endpoint (connection #PID<0.18307.0>, stream id 1) terminated
Server: api.v1.gwscan.com:80 (http)
Request: GET /Templates/user/finance/css/userPay.css
** (exit) an exception was raised:
    ** (Phoenix.Template.UndefinedError) Could not render "404.html" for GodwokenExplorerWeb.ErrorView, please define a matching clause for render/2 or define a template at "lib/godwoken_explorer_web/templates/error/*". No templates were compiled for this module.
Assigns:

%{conn: %Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{kind: :error, layout: false, reason: %Phoenix.Router.NoRouteError{conn: %Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{}, body_params: %{}, cookies: %{}, halted: false, host: "api.v1.gwscan.com", method: "GET", owner: #PID<0.18308.0>, params: %{}, path_info: ["Templates", "user", "finance", "css", "userPay.css"], path_params: %{}, port: 80, private: %{GodwokenExplorerWeb.Router => {[], %{GodwokenExplorerWeb.API.RPC.RPCTranslator => []}}, :before_send => [#Function<0.23023616/1 in Plug.Telemetry.call/2>], :phoenix_endpoint => GodwokenExplorerWeb.Endpoint, :phoenix_request_logger => {"request_logger", "request_logger"}, :phoenix_router => GodwokenExplorerWeb.Router, :plug_session_fetch => #Function<1.77458138/1 in Plug.Session.fetch_session/1>}, query_params: %{}, query_string: "", remote_ip: {172, 19, 0, 1}, req_cookies: %{}, req_headers: [{"accept", "application/json,*/*"}, {"accept-encoding", "gzip, deflate"}, {"accept-language", "zh"}, {"connection", "close"}, {"content-type", "application/x-www-form-urlencoded"}, {"host", "api.v1.gwscan.com"}, {"referer", "https://api.v1.gwscan.com:443/Templates/user/finance/css/userPay.css"}, {"user-agent", "Mozilla/5.0 (Linux; Android 8.1; EML-L29 Build/HUAWEIEML-L29; xx-xx) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/65.0.3325.109 Mobile Safari/537.36 (iPad; iPhone; CPU iPhone OS 13_2_3 like Mac OS X)"}, {"x-forwarded-for", "152.32.251.68, 172.31.4.230"}, {"x-forwarded-proto", "https"}, {"x-real-ip", "172.31.4.230"}], request_path: "/Templates/user/finance/css/userPay.css", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "FxVsIgD6w23a1P0ADWOC"}, {"access-control-allow-origin", "*"}, {"access-control-expose-headers", ""}, {"access-control-allow-credentials", "true"}], scheme: :http, script_name: [], secret_key_base: :..., state: :unset, status: nil}, message: "no route found for GET /Templates/user/finance/css/userPay.css (GodwokenExplorerWeb.Router)", plug_status: 404, router: GodwokenExplorerWeb.Router}, stack: [{GodwokenExplorerWeb.Router, :call, 2, [file: 'lib/phoenix/router.ex', line: 406]}, {GodwokenExplorerWeb.Endpoint, :plug_builder_call, 2, [file: 'lib/godwoken_explorer_web/endpoint.ex', line: 1]}, {GodwokenExplorerWeb.Endpoint, :"call (overridable 3)", 2, [file: 'lib/godwoken_explorer_web/endpoint.ex', line: 1]}, {GodwokenExplorerWeb.Endpoint, :call, 2, [file: 'lib/godwoken_explorer_web/endpoint.ex', line: 1]}, {Phoenix.Endpoint.Cowboy2Handler, :init, 4, [file: 'lib/phoenix/endpoint/cowboy2_handler.ex', line: 54]}, {:cowboy_handler, :execute, 2, [file: '/app/deps/cowboy/src/cowboy_handler.erl', line: 37]}, {:cowboy_stream_h, :execute, 3, [file: '/app/deps/cowboy/src/cowboy_stream_h.erl', line: 306]}, {:cowboy_stream_h, :request_process, 3, [file: '/app/deps/cowboy/src/cowboy_stream_h.erl', line: 295]}], status: 404}, body_params: %{}, cookies: %{}, halted: false, host: "api.v1.gwscan.com", meth
```

**Comment by zmcNotafraid** [comment]
- [ ] rpc is possibility of failure
```
2022-09-17 03:56:30.969 [error] GenServer #PID<0.22642.1> terminating
** (CaseClauseError) no case clause matching: {:ok, nil}
    (godwoken_explorer 0.1.0) lib/godwoken_rpc/block.ex:86: GodwokenRPC.Block.elixir_to_transactions/1
    (elixir 1.13.1) lib/enum.ex:4086: Enum.flat_map_list/2
    (godwoken_explorer 0.1.0) lib/godwoken_rpc/blocks.ex:30: GodwokenRPC.Blocks.from_responses/2
    (godwoken_explorer 0.1.0) lib/godwoken_rpc/godwoken_rpc.ex:74: GodwokenRPC.fetch_blocks_by_params/2
    (godwoken_explorer 0.1.0) lib/godwoken_indexer/block/sync_worker.ex:83: GodwokenIndexer.Block.SyncWorker.fetch_and_import/1
    (godwoken_explorer 0.1.0) lib/godwoken_indexer/block/sync_worker.ex:55: GodwokenIndexer.Block.SyncWorker.handle_info/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:771: :gen_server.handle_msg/6
```

**Comment by zmcNotafraid** [comment]
- [ ] favicon.icon
```
2022-10-09 01:26:59.665 [error] #PID<0.9775.2> running GodwokenExplorerWeb.Endpoint (connection #PID<0.9774.2>, stream id 1) terminated
Server: api.v1.gwscan.com:80 (http)
Request: GET /favicon.ico
** (exit) an exception was raised:
    ** (Phoenix.Template.UndefinedError) Could not render "404.html" for GodwokenExplorerWeb.ErrorView, please define a matching clause for render/2 or define a template at "lib/godwoken_explorer_web/templates/error/*". No templates were compiled for this module.
Assigns:
```
