### ISSUE TITLE
graphql visit udt account return 500

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/godwoken_explorer#1091]
graphql visit this account return 500
eth_address: 0x8375e0901419481ad87ec8a2834f1a85f6d19143
```
2022-10-17 02:21:08.422 [error] #PID<0.4248.0> running GodwokenExplorerWeb.Endpoint (connection #PID<0.4247.0>, stream id 1) terminated
Server: api.v1-betanet.gwscan.com:80 (http)
Request: POST /graphql
** (exit) an exception was raised:
    ** (Ecto.MultipleResultsError) expected at most one result but got 2 in query:

from s0 in GodwokenExplorer.SmartContract,
  where: s0.account_id == ^80712

        (ecto 3.7.1) lib/ecto/repo/queryable.ex:149: Ecto.Repo.Queryable.one/3
        (godwoken_explorer 0.1.0) lib/godwoken_explorer/graphql/resolovers/account.ex:98: GodwokenExplorer.Graphql.Resolvers.Account.smart_contract/3
        (absinthe 1.7.0) lib/absinthe/resolution.ex:209: Absinthe.Resolution.call/2
        (absinthe 1.7.0) lib/absinthe/phase/document/execution/resolution.ex:230: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
        (absinthe 1.7.0) lib/absinthe/phase/document/execution/resolution.ex:185: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/3
        (absinthe 1.7.0) lib/absinthe/phase/document/execution/resolution.ex:170: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe 1.7.0) lib/absinthe/phase/document/execution/resolution.ex:88: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe 1.7.0) lib/absinthe/phase/document/execution/resolution.ex:280: Absinthe.Phase.Document.Execution.Resolution.build_result/3
```

**Comment by zmcNotafraid** [comment]
smart contract bind 2 records with this account
