### ISSUE TITLE
testnet account not create

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/godwoken_explorer#1144]
```
2022-11-13 08:18:17.249 [error] Fetch account succeed.But is nil!!!:0x24795de0d48a06418d2e55b2b2093fec2dae9975a821b8a3e8566aee21abfbc1
2022-11-13 08:18:17.249 [error] GenServer #PID<0.25912.2> terminating
** (MatchError) no match of right hand side value: {:error, :account_slow}
    (godwoken_explorer 0.1.0) lib/godwoken_explorer/account.ex:443: GodwokenExplorer.Account.find_or_create_contract_by_eth_address/1
    (godwoken_explorer 0.1.0) lib/godwoken_indexer/block/sync_worker.ex:629: anonymous fn/1 in GodwokenIndexer.Block.SyncWorker.handle_tx_generated_contract/1
    (elixir 1.13.1) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
    (godwoken_explorer 0.1.0) lib/godwoken_indexer/block/sync_worker.ex:234: GodwokenIndexer.Block.SyncWorker.handle_polyjuice_transactions/1
    (godwoken_explorer 0.1.0) lib/godwoken_indexer/block/sync_worker.ex:108: GodwokenIndexer.Block.SyncWorker.fetch_and_import/1
    (godwoken_explorer 0.1.0) lib/godwoken_indexer/block/sync_worker.ex:65: GodwokenIndexer.Block.SyncWorker.handle_info/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:771: :gen_server.handle_msg/6
Last message: {:work, 807025}
```

**Comment by Keith-CY** [comment]
PR: https://github.com/Magickbase/godwoken_explorer/pull/1145#issuecomment-1312669406
