### ISSUE TITLE
Sync worker  fetch_eth_hash_by_gw_hash rpc failed

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/godwoken_explorer#1181]
** (MatchError) no match of right hand side value: {:ok, %GodwokenRPC.Transaction.FetchedEthHashByGwHashes{errors: [%{code: -32603, data: %{gw_tx_hash: "0xd99499b8fe344f8bfeb9715a63ac18f61f09af9abc76e6b74feb62f790150394"}, message: "Internal error"}], params_list: []}}
    (godwoken_explorer 0.1.0) lib/godwoken_indexer/block/sync_worker.ex:215: GodwokenIndexer.Block.SyncWorker.handle_polyjuice_transactions/1
    (godwoken_explorer 0.1.0) lib/godwoken_indexer/block/sync_worker.ex:108: GodwokenIndexer.Block.SyncWorker.fetch_and_import/1
    (godwoken_explorer 0.1.0) lib/godwoken_indexer/block/sync_worker.ex:65: GodwokenIndexer.Block.SyncWorker.handle_info/2
    (stdlib 3.17) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:work, 255321}

**Comment by zmcNotafraid** [comment]
web3 indexer Redis not set password
