### ISSUE TITLE
ERC721 token instance metadata cause resource leak

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/godwoken_explorer#1551]
Call gw rpc "gw_execute_raw_l2transaction" error: JSONRPCError: server error {"code":-32600,"message":"invalid exit code 3","data":{"block_number":"0x44b44b","exit_code":"0x3","last_log":{"account_id":"0x26a19","data":"0x20bcbe000000000020bcbe0000000000000000000000000000000000000000000000000003000000","service_flag":"0x2"},"return_data":"0x","tx_hash":"0x072493667766fe89804439e81c9cca9620efea072cefa7898aa2270a45cd5628"}}
2023-10-24T00:30:40.570Z [error]: JSONRPC Server Error: [bound call] RpcError: out of gas RpcError: out of gas
    at handleErrorTxReceipt (/godwoken-web3/packages/api-server/lib/methods/gw-error.js:127:11)
    at Object.handleGwError (/godwoken-web3/packages/api-server/lib/methods/gw-error.js:53:13)
    at Eth.call (/godwoken-web3/packages/api-server/lib/methods/modules/eth.js:319:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Eth.call (/godwoken-web3/packages/api-server/lib/methods/validator.js:36:20)
    at async methods.<computed> (/godwoken-web3/packages/api-server/lib/methods/index.js:49:36)

**Comment by zmcNotafraid** [comment]
The reason is some udt we identify as erc721,but when we call eth_call to get their balance, they return out of gas error.
