### ISSUE TITLE
Cannot read properties of null (reading 'slice')

### ISSUE THREAD

**Issue by Flouse** [Magickbase/godwoken_explorer#783]
https://v1.testnet.gwscan.com/

![image](https://user-images.githubusercontent.com/1297478/180628927-cdcedc82-ee09-4df5-a5b8-dc42f9c30554.png)

```js
TypeError: Cannot read properties of null (reading 'slice')
    at index-bb0fa73e2ad429d9.js:1:8124
    at Array.map (<anonymous>)
    at Q (index-bb0fa73e2ad429d9.js:1:7259)
    at oo (framework-bb5c596eafb42b22.js:1:59416)
    at Wo (framework-bb5c596eafb42b22.js:1:68983)
    at Ku (framework-bb5c596eafb42b22.js:1:112707)
    at Li (framework-bb5c596eafb42b22.js:1:98957)
    at Ni (framework-bb5c596eafb42b22.js:1:98885)
    at Pi (framework-bb5c596eafb42b22.js:1:98748)
    at bi (framework-bb5c596eafb42b22.js:1:95714)
```

**Comment by Keith-CY** [comment]
`slice` at `1:8124` is located in `concat(e.eth_hash.slice(0,8),"...")`, is `eth_hash` possibly to be `null` @Naupio

**Comment by Naupio** [comment]
> 

I checking the database resource find that there are some tx record of eth_hash field with null

**Comment by Keith-CY** [comment]
`eth_hash` is `null` when tx is not one of `polyjuice`, `polyjuice_creator`, `eth_address_registry`, it's been fixed by use `gw_hash` as fallback
